### ISSUE TITLE
Big binary files in repo?

### ISSUE THREAD

**Issue by rgerkin** [JustasB/OlfactoryBulb#3]
@JustasB I am cloning this repo right now and it is huge.  There are [some tools](https://rtyley.github.io/bfg-repo-cleaner/) that can check your git commit history for large binary files (which generally don't need to be there) and then delete them.    Russell and I did this for NeuronUnit a while back.  You should considering doing this to reduce a barrier to use of your model (especially for developers).  A tarball of the head of the master branch is probably not nearly as big, but wouldn't be enough for someone who wanted to make commits and PRs.

**Comment by JustasB** [comment]
Thanks for reporting the issue @rgerkin. I've been working on packaging the model so that downloading the whole repo would not be necessary. When ready, the download size should be around 100MB to run the model.

**Comment by JustasB** [comment]
I will also clean up the repo history as you suggested.

**Comment by JustasB** [comment]
This should be fixed. Repo size is ~300MB
