### ISSUE TITLE
Importing with exec not behaving as intended

### ISSUE THREAD

**Issue by rgerkin** [JustasB/OlfactoryBulb#4]
I have been unable to run:
```
from prev_ob_models.Birgiolas2020.isolated_cells import *
cell = MC1()
```
due to:
```
Traceback (most recent call last):
  File "/home/rgerkin/OlfactoryBulb/prev_ob_models/Birgiolas2020/isolated_cells.py", line 40, in __init__
    Transform.apply_on(str(self.cell))
NameError: name 'Transform' is not defined
```

It appears that [this line](https://github.com/JustasB/OlfactoryBulb/blob/b1ec57645f0cf8844c8ecfaa05753850bc4d01be/prev_ob_models/Birgiolas2020/isolated_cells.py#L39) which attempts to import a Transformer via exec and a concatenated string does not work.  In debugging it, it does appear to be creating the correct command to exec, and that command works if pasted in a Python terminal in the same context.  However, it may be that some Python versions or kernels do not respect imports via exec.  This should probably be replaced with a more robust import-by-name system such as the built-in `importlib` module.

**Comment by JustasB** [comment]
It could be a python version issue. The model was developed in 2.7. Which python version were you using?

**Comment by rgerkin** [comment]
3.7.  Even Numpy won't be supporting Python 2 past tomorrow, so it would be good to target Python 3 compatibility.

**Comment by JustasB** [comment]
I'll take a look

**Comment by JustasB** [comment]
The model code should now work with python 2 and 3. Let me know if you run into other issues.
