### ISSUE TITLE
Too big to download as data files maybe included.

### ISSUE THREAD

**Issue by russelljjarvis** [JustasB/OlfactoryBulb#5]
I am not sure if this repository is intended for public consumption. The repository takes a prohibitively long time to download. The likely reason is source code and data files are packaged together.

**Comment by JustasB** [comment]
Have you tried shallow clone?

https://linuxhint.com/git-shallow-clone-and-clone-depth/

**Comment by russelljjarvis** [comment]
No but trying it now. Sorry I realise now I duplicated a different issue.

https://github.com/JustasB/OlfactoryBulb/issues/3

**Comment by russelljjarvis** [comment]
Still would take hours to download at shallow clone levels 1-3.

**Comment by JustasB** [comment]
Give it a try again, I've cleaned up the repo history and reduced the repo size. 

![image](https://user-images.githubusercontent.com/10732358/85134942-3dd56100-b20b-11ea-8b8f-3d656dd2893b.png)
