### ISSUE TITLE
Error trying to run model

### ISSUE THREAD

**Issue by ellismith** [JustasB/OlfactoryBulb#6]
Hello! (I'm Elli, Rick's new grad student) @rgerkin
I started going through the documentation so that I can run the model for the first time, and am encountering an error.  When I get to the point that says "On the right panel of Jupyter Lab, find the notebooks folder and open the LFP Wavelet Analysis notebook. Then run all the cells of the notebook." I was able to get everything into Jupyter and open the notebooks just fine but was struggling with the run all cells step. I tried a few times and after a pretty long time loading I eventually got this error, not too sure what it means.
<img width="1180" alt="Screen Shot 2020-10-03 at 11 15 03 AM" src="https://user-images.githubusercontent.com/66271130/95027283-28fecb00-064c-11eb-8b57-43130d77083e.png">

**Comment by rgerkin** [comment]
@JustasB This is on the lab JupyterHub on Spike, so I manage all the packages.  I'm wondering if a file got truncated or maybe a default encoding got changed across package versions?

**Comment by JustasB** [comment]
Hi @ellismith, welcome to @rgerkin 's lab!

Hmmm, I can't reproduce the issue. I suspect it might be related to package/python versions.

Some steps that may aid debugging:

 a) Test if the Dockerized version is able to get past the above step (steps: https://docs.olfactorybulb.org/gettingstarted.html)
 b) If it does, then there is some difference between your machine environment and the model's docker environment.

The model docker image builds on these two Docker files:

 - https://github.com/JustasB/neuron-docker/blob/master/v7.7/Dockerfile
 - https://github.com/JustasB/OlfactoryBulb/blob/master/docker/obmodel/Dockerfile

You can also try comparing package/python versions on your machine to those on the model Docker image to try to narrow down the source of the problem.

**Comment by JustasB** [comment]
Actually, upon closer look, I get the same error. The problem is with the `with open(...) as f` lines in the LFP Analysis notebook.

In the notebook, append an `rb` parameter to the three `open with...` lines, so they end like `'), 'rb') as f:`. For example, the first `open with` line should look like this:

```
 with open(os.path.join(result_dir, 'input_times.pkl'), 'rb') as f:
```

Then add the last `rb` to the other `open with` lines.

Once the `rb` parameter is added, rerun the cell with `show_plots('GammaSignature', sniff_count=8)` to see the plots.

**Comment by rgerkin** [comment]
The 'rb' part makes sense.  The b is for binary, and ar some point either Python or some package switched from a text encoding to a binary encoding by default so now that has to be made explicitly in the unpickling.

**Comment by JustasB** [comment]
And here I thought Docker was going to save us all from from such problems... 

![sad parrot](https://vignette.wikia.nocookie.net/partyparrot/images/b/b1/Sadparrot.gif/revision/latest?cb=20170401184704)

**Comment by ellismith** [comment]
Hi Justas,
I made those edits and got it working successfully! Thank you so much, I
really appreciate your help! (:
Elli

**Comment by ellismith** [comment]
Hi Justas,
I made those edits with adding rb parameters and got it working successfully! Thank you so much, I really appreciate your help! (:

**Comment by JustasB** [comment]
@ellismith Glad to help!
